### PR TITLE
add setting force keep the number sequence

### PR DESCRIPTION
**Pull request by boldenamsterdam**

### CODE REVIEW

**Comment by bossanova808** [comment]
Hey

Thanks!

But, and I may not have though this through enough, wouldn't it be a lot simpler just to check the setting and if there is already an order number here: https://github.com/bossanova808/CommerceFriendlyOrderNumbers/blob/fb10101f131228597907c9703dede75d1714ce4e/commercefriendlyordernumbers/services/CommerceFriendlyOrderNumbersService.php#L49

Basically, if ($order->friendlyOrderNumber && force_keep_sequence) then don't getNextOrderNumber otherwise do?

Only one order can ever get a particular number, it's incremented each time...so, there doesn't seem to be any chance of re-used numbers and thus it seems like two queries that aren't needed?

As I say I may not have thought it through enough but that is what I had in mind....

**Comment by boldenamsterdam** [comment]
I get your point. It is actually a good improvement to make sure no overwrite occurs but then `if ($order->friendlyOrderNumber)` is enough. It may even solve the problem but I am not sure if it is 100% failproof. 

*Scenario:*  
order A has no number
event `orderBeforeComplete` is triggered
order number is increased
a fail occurs and order is not saved
order A still no number
event `orderBeforeComplete` is triggered again
order number is increased again because order has no number

So we skip a number here..

**Comment by bossanova808** [comment]
Hmm, it would have to be a fail on the order save right there, but I take your point.

Have you tested this fairly properly then?

Also - care to write the docs for the feature as part of the PR?

I note you've done this in master rather than the dev branch I created for you..?

**Comment by boldenamsterdam** [comment]
Yes it has been tested.
I will update docs as well.
At the end I could fork it from master.

**Comment by bossanova808** [comment]
Ok - sorry, lost track of this one a bit.  Just want to re-confirm this has been used in production for a while without issues?  If so then I will merge and do a release.

**Comment by boldenamsterdam** [comment]
Hello, 

Yes we have the fix to a couple of clients released. So far no problem.

**Comment by bossanova808** [comment]
Just a heads up - I'm coming out of my summer slumber, and I am going to merge this but I have decided to make this the default behaviour and not have a setting because I can't see any disadvantage to it really...feel free to update your PR for that, but otherwise I'll do it soon.

**Pull request merged**
